### ISSUE TITLE
[feature] Add the `Possible Awards` field too

### ISSUE THREAD

**Issue by bugbaba** [infinityhacked/openbugbounty-targets#1]
Hey,

Firstly, thanks for collecting this and putting it up in json format.

All the programs have `Possible Awards` section, it would be great if you can also add those in the data that would be great.

And I am just curious, are you doing this manually or have automated the parsing of the program pages ?

--
Thanks
bugbaba

**Comment by infinityhacked** [comment]
Awards section added to json.

I am using python script to parse programs. Will share source soon in this repo.
